% Define the variable names as provided
variableNames = { ...
    'Sentiment Count', ...
    'Financial Stability', ...
    'Financial Liability', ...
    'Afinn', ...
    'Harvard-IV', ...
    'Sentiment TFM', ...
    'Sentiment TF-IDF', ...
    'VADER', ...
    'Opinion Sentiment', ...
    'BERT'};

% Open a file for writing the LaTeX table rows
fid = fopen('GrangerTableContent.txt', 'w');

% Loop through each variable and write a table row
for i = 1:length(variableNames)
    % Compute truncated values to two decimals
    val1 = floor(results(i,2,1) * 100) / 100;
    val2 = floor(results(i,2,2) * 100) / 100;
    line = sprintf('\\textbf{%s} & %.2f & %.2f \\\\\n', variableNames{i}, val1, val2);
    fprintf(fid, '%s', line);
end

% Close the file
fclose(fid);
