function [MSPE]=print_MSPE(msfe,j)

ind = 1;
int = 2;

MSPE=[round(squeeze((msfe(j,1,ind)))./squeeze((msfe(j,1,int))),3)' ...
      round(squeeze((msfe(j,3,ind)))./squeeze((msfe(j,3,int))),3)' ...
      round(squeeze((msfe(j,6,ind)))./squeeze((msfe(j,6,int))),3)' ...
      round(squeeze((msfe(j,12,ind)))./squeeze((msfe(j,12,int))),3)' ...
      round(squeeze((msfe(j,24,ind)))./squeeze((msfe(j,24,int))),3)'];

 