function [MSPE]=print_MSPE(msfe)

ind = [1 2];
int = [3 4];

MSPE=[round(squeeze(mean(msfe(1:end,1,ind)))./squeeze(mean(msfe(1:end,1,int))),3)' ...
      round(squeeze(mean(msfe(1:end-2,3,ind)))./squeeze(mean(msfe(1:end-2,3,int))),3)' ...
      round(squeeze(mean(msfe(1:end-5,6,ind)))./squeeze(mean(msfe(1:end-5,6,int))),3)' ...
      round(squeeze(mean(msfe(1:end-11,12,ind)))./squeeze(mean(msfe(1:end-11,12,int))),3)' ...
      round(squeeze(mean(msfe(1:end-23,24,ind)))./squeeze(mean(msfe(1:end-23,24,int))),3)'];

 