function printLatex(T)

Tarr=table2array(T);
cat(2,num2str(Tarr(1,1)),' & ',' & ',num2str(Tarr(2,1)),' & ',...
      num2str(Tarr(1,2)),' & ',' & ',num2str(Tarr(2,2)),' & ',...
      num2str(Tarr(1,3)),' & ',' & ',num2str(Tarr(2,3)),' & ',...
      num2str(Tarr(1,4)),' & ',' & ',num2str(Tarr(2,4)),' & ',...
      num2str(Tarr(1,5)),' & ',' & ',num2str(Tarr(2,5)))

end