function T=print_MSPE(msfe)
models = {'MSPE-WTI';'MSPE-RAC';'MSPE-BRENT';};
horizons = {'Horizon1';'Horizon3';'Horizon6';'Horizon12';'Horizon24'};
ind = [1 2 3];
int = [4 5 6];
T=table(round(squeeze(mean(msfe(1:end,1,ind)))./squeeze(mean(msfe(1:end,1,int))),3),...
   round(squeeze(mean(msfe(1:end-2,3,ind)))./squeeze(mean(msfe(1:end-2,3,int))),3),...
   round(squeeze(mean(msfe(1:end-5,6,ind)))./squeeze(mean(msfe(1:end-5,6,int))),3),...
   round(squeeze(mean(msfe(1:end-11,12,ind)))./squeeze(mean(msfe(1:end-11,12,int))),3),...
   round(squeeze(mean(msfe(1:end-23,24,ind)))./squeeze(mean(msfe(1:end-23,24,int))),3),'RowNames',models,'VariableNames',horizons);
    